INSERT INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
(11129, 'You don''t have enough %ss', NULL, 'Tu n''as pas assez de %ss', NULL, NULL, NULL, NULL, NULL, NULL),
(11128, 'Using this item for transmogrify will bind it to you and make it non-refundable and non-tradeable.\r\nDo you wish to continue?\r\n\r\n', NULL, 'L''utilisation de cette item pour la transmogrification, va le lié à vous le rendant non-remboursables et non échangeables.\r\n\r\nVoulez-vous continuer?', NULL, NULL, NULL, NULL, NULL, NULL),
(11127, 'Remove transmogrification from %s?', NULL, 'Supprimer la transmogrification pour %s?', NULL, NULL, NULL, NULL, NULL, NULL),
(11126, 'Remove transmogrification', NULL, 'Supprimer la transmogrification', NULL, NULL, NULL, NULL, NULL, NULL),
(11125, 'Update menu', NULL, 'Mise à jour Menu', NULL, NULL, NULL, NULL, NULL, NULL),
(11124, 'Remove transmogrifications from all equipped items?', NULL, 'Supprimer les transmogrifications de tous les items équipés?', NULL, NULL, NULL, NULL, NULL, NULL),
(11123, 'Remove all transmogrifications', NULL, 'Supprimer toutes les transmogrifications', NULL, NULL, NULL, NULL, NULL, NULL),
(11122, 'Back..', NULL, 'Retour..', NULL, NULL, NULL, NULL, NULL, NULL),
(11121, 'Tabard', NULL, 'Tabard', NULL, NULL, NULL, NULL, NULL, NULL),
(11120, 'Ranged', NULL, 'À distance', NULL, NULL, NULL, NULL, NULL, NULL),
(11119, 'Off hand', NULL, 'Main Gauche', NULL, NULL, NULL, NULL, NULL, NULL),
(11118, 'Main hand', NULL, 'Main Droite', NULL, NULL, NULL, NULL, NULL, NULL),
(11117, 'Back', NULL, 'Retour', NULL, NULL, NULL, NULL, NULL, NULL),
(11116, 'Hands', NULL, 'Deux Mains', NULL, NULL, NULL, NULL, NULL, NULL),
(11115, 'Wrists', NULL, 'Poignets', NULL, NULL, NULL, NULL, NULL, NULL),
(11114, 'Feet', NULL, 'Pieds', NULL, NULL, NULL, NULL, NULL, NULL),
(11113, 'Legs', NULL, 'Jambes', NULL, NULL, NULL, NULL, NULL, NULL),
(11112, 'Waist', NULL, 'Ceinture', NULL, NULL, NULL, NULL, NULL, NULL),
(11111, 'Chest', NULL, 'Torse', NULL, NULL, NULL, NULL, NULL, NULL),
(11110, 'Shirt', NULL, 'Chemise', NULL, NULL, NULL, NULL, NULL, NULL),
(11109, 'Shoulders', NULL, 'Épaules', NULL, NULL, NULL, NULL, NULL, NULL),
(11108, 'Head', NULL, 'Tête', NULL, NULL, NULL, NULL, NULL, NULL),
(11107, 'Equipment slot is empty', NULL, 'L’emplacement d''équipement est vide', NULL, NULL, NULL, NULL, NULL, NULL),
(11106, 'Selected item does not exist', NULL, 'L''item sélectionné n''existe pas', NULL, NULL, NULL, NULL, NULL, NULL),
(11105, 'Selected items are not suitable', NULL, 'L''item sélectionné n''est pas appropriés', NULL, NULL, NULL, NULL, NULL, NULL),
(11104, '%s transmogrified', NULL, '%s transmogrifié', NULL, NULL, NULL, NULL, NULL, NULL),
(11103, 'No transmogrification on %s slot', NULL, 'Pas de transmogrification à l''emplacement %s', NULL, NULL, NULL, NULL, NULL, NULL),
(11102, '%s transmogrification removed', NULL, '%s transmogrification supprimé', NULL, NULL, NULL, NULL, NULL, NULL),
(11101, 'You have no transmogrified items equipped', NULL, 'Tu n''as pas d''items équipés à transmogrifié', NULL, NULL, NULL, NULL, NULL, NULL),
(11100, 'Transmogrifications removed from equipped items', NULL, 'Transmogrification supprimé sur les items équipés', NULL, NULL, NULL, NULL, NULL, NULL);

